services:
  postgres:
    image: postgres:17
    container_name: frugo-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: frugo
      POSTGRES_USER: frugo
      POSTGRES_PASSWORD: frugo

    ports:
      - "5432:5432"

    volumes:
      - frugo-postgres-data:/var/lib/postgresql/data

volumes:
  frugo-postgres-data: