spring.application.name=frugoBE

spring.datasource.url=jdbc:postgresql://localhost:5432/frugo
spring.datasource.username=frugo
spring.datasource.password=frugo

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true