CREATE TABLE purchase_order_status_history (
                                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               purchase_order_id INTEGER NOT NULL,
                                               old_status_id INTEGER NULL,
                                               new_status_id INTEGER NOT NULL,
                                               employee_id INTEGER NULL,
                                               note TEXT NULL,
                                               changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                               CONSTRAINT fk_po_status_history_order
                                                   FOREIGN KEY (purchase_order_id)
                                                       REFERENCES purchase_order(id),

                                               CONSTRAINT fk_po_status_history_old_status
                                                   FOREIGN KEY (old_status_id)
                                                       REFERENCES status(id),

                                               CONSTRAINT fk_po_status_history_new_status
                                                   FOREIGN KEY (new_status_id)
                                                       REFERENCES status(id),

                                               CONSTRAINT fk_po_status_history_employee
                                                   FOREIGN KEY (employee_id)
                                                       REFERENCES employee(id)

);

INSERT INTO purchase_order_status_history(
    purchase_order_id,
    old_status_id,
    new_status_id,
    employee_id,
    note,
    changed_at
)
VALUES
    (
     1,
     null,
     1,
     1,
     'Vytvoření objednávky',
     '2026-08-20 08:15:00'
    ),
    (
    1,
       1,
       2,
       null,
       'Přijetí prvního zboží nákupní objednávky',
        '2026-08-21 09:20:00'
    ),
    (
     1,
     2,
     4,
     null,
     'Přijetí veškerého objednaného množství',
    '2026-08-21 10:00:00'
    ),
    (
     2,
     null,
     1,
     1,
     'Vytvoření objednávky',
     '2026-08-22 10:30:00'
    ),
    (
    2,
    1,
     2,
     null,
     'Přijetí prvního zboží nákupní objednávky',
    '2026-08-23 11:15:00'
    ),
    (
     3,
     null,
     1,
     1,
     'Vytvoření objednávky',
     '2026-08-25 14:20:00'
    ),
    (
     4,
     null,
     1,
     1,
     'Vytvoření objednávky',
     '2026-08-28 09:45:00'
    ),
    (
     4,
     1,
     5,
     1,
     'Zrušení objednávky',
     '2026-08-28 10:00:00'
    );