-- ============================================================
-- FRUGO DATABASE - V1
-- Initial database schema
-- ============================================================


-- ============================================================
-- BASIC / REFERENCE TABLES
-- ============================================================

CREATE TABLE category (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR NOT NULL UNIQUE,
                          code VARCHAR NOT NULL UNIQUE
);

CREATE TABLE packaging (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           code VARCHAR NOT NULL UNIQUE,
                           name VARCHAR NOT NULL UNIQUE,
                           description VARCHAR
);

CREATE TABLE country (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         code VARCHAR NOT NULL UNIQUE,
                         name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE status (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code VARCHAR NOT NULL UNIQUE,
                        name VARCHAR NOT NULL UNIQUE,
                        description VARCHAR
);

CREATE TABLE shift (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       code VARCHAR NOT NULL UNIQUE,
                       description VARCHAR
);


-- ============================================================
-- WAREHOUSE
-- ============================================================

CREATE TABLE warehouse (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           code VARCHAR NOT NULL UNIQUE,
                           name VARCHAR NOT NULL UNIQUE,
                           description VARCHAR
);

CREATE TABLE sector_type (
                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             code VARCHAR NOT NULL UNIQUE,
                             name VARCHAR NOT NULL UNIQUE,
                             description VARCHAR
);

CREATE TABLE sector (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        warehouse_id INTEGER NOT NULL,
                        code VARCHAR NOT NULL,
                        name VARCHAR NOT NULL,
                        type_id INTEGER NOT NULL,
                        description VARCHAR,

                        CONSTRAINT uq_sector_warehouse_code
                            UNIQUE (warehouse_id, code),

                        CONSTRAINT uq_sector_warehouse_name
                            UNIQUE (warehouse_id, name)
);

CREATE TABLE location (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sector_id INTEGER NOT NULL,
                          code VARCHAR NOT NULL,
                          aisle INTEGER,
                          rack INTEGER,
                          level INTEGER,
                          position INTEGER,
                          can_be_ordered BOOLEAN NOT NULL,

                          CONSTRAINT uq_location_sector_code
                              UNIQUE (sector_id, code)
);


-- ============================================================
-- PRODUCTS
-- ============================================================

CREATE TABLE product_type (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              category_id INTEGER NOT NULL,
                              name VARCHAR NOT NULL,

                              CONSTRAINT uq_product_type_category_name
                                  UNIQUE (category_id, name)
);

CREATE TABLE product (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         product_type_id INTEGER NOT NULL,
                         product_code VARCHAR NOT NULL UNIQUE,
                         name VARCHAR NOT NULL,
                         price_per_unit DECIMAL(10,2) NOT NULL,
                         shelf_life_days INTEGER NOT NULL,
                         is_for_sale BOOLEAN NOT NULL
);

CREATE TABLE warehouse_item (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                product_id INTEGER NOT NULL,
                                eti_number VARCHAR NOT NULL UNIQUE,
                                packaging_id INTEGER NOT NULL,
                                quantity_per_package INTEGER NOT NULL,
                                subpackaging_id INTEGER,
                                quantity_per_subpackage INTEGER,
                                location_id INTEGER NOT NULL,
                                quantity INTEGER NOT NULL,
                                country_of_origin_id INTEGER NOT NULL,
                                received_at TIMESTAMP NOT NULL,
                                expiration_date DATE NOT NULL,
                                allocated_quantity INTEGER NOT NULL DEFAULT 0
);


-- ============================================================
-- CUSTOMER / ORDERS
-- ============================================================

CREATE TABLE customer (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR NOT NULL,
                          company_id VARCHAR UNIQUE,
                          street VARCHAR NOT NULL,
                          house_number VARCHAR NOT NULL,
                          city VARCHAR NOT NULL,
                          postal_code VARCHAR NOT NULL,
                          country_id INTEGER NOT NULL,
                          is_registered BOOLEAN NOT NULL
);

CREATE TABLE orders (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_number VARCHAR NOT NULL UNIQUE,
                        customer_id INTEGER NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        status_id INTEGER NOT NULL
);

CREATE TABLE order_items (
                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id INTEGER NOT NULL,
                             warehouse_item_id INTEGER NOT NULL,
                             quantity INTEGER NOT NULL,
                             picked_quantity INTEGER NOT NULL DEFAULT 0,
                             status_id INTEGER NOT NULL
);


-- ============================================================
-- EMPLOYEES / RBAC
-- ============================================================

CREATE TABLE department (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR NOT NULL UNIQUE,
                            code VARCHAR NOT NULL UNIQUE,
                            description VARCHAR
);

CREATE TABLE job_position (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              department_id INTEGER NOT NULL,
                              code VARCHAR NOT NULL UNIQUE,
                              name VARCHAR NOT NULL UNIQUE,
                              description VARCHAR
);

CREATE TABLE employee (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR NOT NULL,
                          last_name VARCHAR NOT NULL,
                          employee_number VARCHAR NOT NULL UNIQUE,
                          address VARCHAR NOT NULL,
                          city VARCHAR NOT NULL,
                          postal_code VARCHAR NOT NULL,
                          shift_id INTEGER NOT NULL,
                          birth_date DATE NOT NULL,
                          hire_date DATE NOT NULL,
                          phone VARCHAR NOT NULL UNIQUE,
                          email VARCHAR NOT NULL UNIQUE,
                          is_active BOOLEAN NOT NULL,
                          termination_date DATE,
                          job_position_id INTEGER NOT NULL,
                          system_username VARCHAR NOT NULL UNIQUE
);

CREATE TABLE employee_login (
                                employee_id INTEGER PRIMARY KEY,
                                username VARCHAR NOT NULL UNIQUE,
                                password_hash VARCHAR NOT NULL
);

CREATE TABLE role (
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code VARCHAR NOT NULL UNIQUE,
                      name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE permission (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            module_id INTEGER NOT NULL,
                            code VARCHAR NOT NULL UNIQUE,
                            name VARCHAR NOT NULL UNIQUE,
                            description VARCHAR NOT NULL
);

CREATE TABLE module (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code VARCHAR NOT NULL UNIQUE,
                        name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE employee_role (
                               employee_id INTEGER NOT NULL,
                               role_id INTEGER NOT NULL,

                               PRIMARY KEY (employee_id, role_id)
);

CREATE TABLE role_permission (
                                 role_id INTEGER NOT NULL,
                                 permission_id INTEGER NOT NULL,

                                 PRIMARY KEY (role_id, permission_id)
);


-- ============================================================
-- PALLETS
-- ============================================================

CREATE TABLE pallet (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        eti_number VARCHAR NOT NULL UNIQUE,
                        location_id INTEGER NOT NULL,
                        is_closed BOOLEAN NOT NULL
);

CREATE TABLE pallet_warehouse_item (
                                       pallet_id INTEGER NOT NULL,
                                       warehouse_item_id INTEGER NOT NULL UNIQUE,

                                       PRIMARY KEY (pallet_id, warehouse_item_id)
);


-- ============================================================
-- SHIPMENTS
-- ============================================================

CREATE TABLE shipment (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          order_id INTEGER NOT NULL UNIQUE,
                          shipment_number VARCHAR NOT NULL UNIQUE,
                          status_id INTEGER NOT NULL
);

CREATE TABLE shipment_item (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               shipment_id INTEGER NOT NULL,
                               pallet_id INTEGER NOT NULL UNIQUE,
                               status_id INTEGER NOT NULL
);


-- ============================================================
-- EVENTS / STOCK MOVEMENTS
-- ============================================================

CREATE TABLE event_definition (
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  code VARCHAR NOT NULL UNIQUE,
                                  name VARCHAR NOT NULL UNIQUE,
                                  description VARCHAR NOT NULL
);

CREATE TABLE stock_movement (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                event_definition_id INTEGER NOT NULL,
                                created_at TIMESTAMP NOT NULL,
                                purchase_order_id INTEGER,
                                warehouse_item_id INTEGER NOT NULL,
                                new_warehouse_item_id INTEGER,
                                quantity INTEGER NOT NULL,
                                from_location_id INTEGER,
                                to_location_id INTEGER,
                                employee_id INTEGER NOT NULL,
                                pallet_id INTEGER,
                                order_id INTEGER,
                                shipment_id INTEGER
);


-- ============================================================
-- PURCHASE ORDERS
-- ============================================================

CREATE TABLE supplier (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR NOT NULL,
                          internal_code VARCHAR NOT NULL UNIQUE
);

CREATE TABLE purchase_order (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                purchase_order_number VARCHAR NOT NULL UNIQUE,
                                supplier_id INTEGER NOT NULL,
                                created_at TIMESTAMP NOT NULL,
                                employee_id INTEGER NOT NULL,
                                status_id INTEGER NOT NULL
);

CREATE TABLE purchase_order_item (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     purchase_order_id INTEGER NOT NULL,
                                     product_id INTEGER NOT NULL,
                                     quantity INTEGER NOT NULL,
                                     received_quantity INTEGER NOT NULL DEFAULT 0,
                                     country_of_origin_id INTEGER NOT NULL,
                                     status_id INTEGER NOT NULL
);


-- ============================================================
-- ETI SEQUENCE
-- ============================================================

CREATE TABLE eti_sequence (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              description VARCHAR NOT NULL,
                              code VARCHAR NOT NULL UNIQUE,
                              last_number INTEGER NOT NULL
);


-- ============================================================
-- EVENT LOG
-- ============================================================

CREATE TABLE event_log (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           event_definition_id INTEGER NOT NULL,
                           created_at TIMESTAMP NOT NULL,
                           employee_id INTEGER,
                           description VARCHAR,
                           data JSONB
);

CREATE TABLE event_log_entity (
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  event_log_id INTEGER NOT NULL,
                                  entity_type VARCHAR NOT NULL,
                                  entity_id INTEGER NOT NULL
);


-- ============================================================
-- FOREIGN KEYS
-- ============================================================

-- Product hierarchy
ALTER TABLE product_type
    ADD CONSTRAINT fk_product_type_category
        FOREIGN KEY (category_id) REFERENCES category(id);

ALTER TABLE product
    ADD CONSTRAINT fk_product_product_type
        FOREIGN KEY (product_type_id) REFERENCES product_type(id);


-- Warehouse
ALTER TABLE sector
    ADD CONSTRAINT fk_sector_warehouse
        FOREIGN KEY (warehouse_id) REFERENCES warehouse(id);

ALTER TABLE sector
    ADD CONSTRAINT fk_sector_type
        FOREIGN KEY (type_id) REFERENCES sector_type(id);

ALTER TABLE location
    ADD CONSTRAINT fk_location_sector
        FOREIGN KEY (sector_id) REFERENCES sector(id);


-- Warehouse items
ALTER TABLE warehouse_item
    ADD CONSTRAINT fk_warehouse_item_product
        FOREIGN KEY (product_id) REFERENCES product(id);

ALTER TABLE warehouse_item
    ADD CONSTRAINT fk_warehouse_item_packaging
        FOREIGN KEY (packaging_id) REFERENCES packaging(id);

ALTER TABLE warehouse_item
    ADD CONSTRAINT fk_warehouse_item_subpackaging
        FOREIGN KEY (subpackaging_id) REFERENCES packaging(id);

ALTER TABLE warehouse_item
    ADD CONSTRAINT fk_warehouse_item_location
        FOREIGN KEY (location_id) REFERENCES location(id);

ALTER TABLE warehouse_item
    ADD CONSTRAINT fk_warehouse_item_country
        FOREIGN KEY (country_of_origin_id) REFERENCES country(id);


-- Customers / orders
ALTER TABLE customer
    ADD CONSTRAINT fk_customer_country
        FOREIGN KEY (country_id) REFERENCES country(id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customer(id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_status
        FOREIGN KEY (status_id) REFERENCES status(id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_warehouse_item
        FOREIGN KEY (warehouse_item_id) REFERENCES warehouse_item(id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_status
        FOREIGN KEY (status_id) REFERENCES status(id);


-- Employees / RBAC
ALTER TABLE employee
    ADD CONSTRAINT fk_employee_shift
        FOREIGN KEY (shift_id) REFERENCES shift(id);

ALTER TABLE employee
    ADD CONSTRAINT fk_employee_job_position
        FOREIGN KEY (job_position_id) REFERENCES job_position(id);

ALTER TABLE employee_login
    ADD CONSTRAINT fk_employee_login_employee
        FOREIGN KEY (employee_id) REFERENCES employee(id);

ALTER TABLE job_position
    ADD CONSTRAINT fk_job_position_department
        FOREIGN KEY (department_id) REFERENCES department(id);

ALTER TABLE permission
    ADD CONSTRAINT fk_permission_module
        FOREIGN KEY (module_id) REFERENCES module(id);

ALTER TABLE employee_role
    ADD CONSTRAINT fk_employee_role_employee
        FOREIGN KEY (employee_id) REFERENCES employee(id);

ALTER TABLE employee_role
    ADD CONSTRAINT fk_employee_role_role
        FOREIGN KEY (role_id) REFERENCES role(id);

ALTER TABLE role_permission
    ADD CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id) REFERENCES role(id);

ALTER TABLE role_permission
    ADD CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id) REFERENCES permission(id);


-- Pallets
ALTER TABLE pallet
    ADD CONSTRAINT fk_pallet_location
        FOREIGN KEY (location_id) REFERENCES location(id);

ALTER TABLE pallet_warehouse_item
    ADD CONSTRAINT fk_pallet_warehouse_item_pallet
        FOREIGN KEY (pallet_id) REFERENCES pallet(id);

ALTER TABLE pallet_warehouse_item
    ADD CONSTRAINT fk_pallet_warehouse_item_warehouse_item
        FOREIGN KEY (warehouse_item_id) REFERENCES warehouse_item(id);


-- Shipments
ALTER TABLE shipment
    ADD CONSTRAINT fk_shipment_order
        FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE shipment
    ADD CONSTRAINT fk_shipment_status
        FOREIGN KEY (status_id) REFERENCES status(id);

ALTER TABLE shipment_item
    ADD CONSTRAINT fk_shipment_item_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipment(id);

ALTER TABLE shipment_item
    ADD CONSTRAINT fk_shipment_item_pallet
        FOREIGN KEY (pallet_id) REFERENCES pallet(id);

ALTER TABLE shipment_item
    ADD CONSTRAINT fk_shipment_item_status
        FOREIGN KEY (status_id) REFERENCES status(id);


-- Stock movements
ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_event_definition
        FOREIGN KEY (event_definition_id) REFERENCES event_definition(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_warehouse_item
        FOREIGN KEY (warehouse_item_id) REFERENCES warehouse_item(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_new_warehouse_item
        FOREIGN KEY (new_warehouse_item_id) REFERENCES warehouse_item(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_from_location
        FOREIGN KEY (from_location_id) REFERENCES location(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_to_location
        FOREIGN KEY (to_location_id) REFERENCES location(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_employee
        FOREIGN KEY (employee_id) REFERENCES employee(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_pallet
        FOREIGN KEY (pallet_id) REFERENCES pallet(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_order
        FOREIGN KEY (order_id) REFERENCES orders(id);

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipment(id);


-- Purchase orders
ALTER TABLE purchase_order
    ADD CONSTRAINT fk_purchase_order_supplier
        FOREIGN KEY (supplier_id) REFERENCES supplier(id);

ALTER TABLE purchase_order
    ADD CONSTRAINT fk_purchase_order_employee
        FOREIGN KEY (employee_id) REFERENCES employee(id);

ALTER TABLE purchase_order
    ADD CONSTRAINT fk_purchase_order_status
        FOREIGN KEY (status_id) REFERENCES status(id);

ALTER TABLE purchase_order_item
    ADD CONSTRAINT fk_purchase_order_item_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id);

ALTER TABLE purchase_order_item
    ADD CONSTRAINT fk_purchase_order_item_product
        FOREIGN KEY (product_id) REFERENCES product(id);

ALTER TABLE purchase_order_item
    ADD CONSTRAINT fk_purchase_order_item_country
        FOREIGN KEY (country_of_origin_id) REFERENCES country(id);

ALTER TABLE purchase_order_item
    ADD CONSTRAINT fk_purchase_order_item_status
        FOREIGN KEY (status_id) REFERENCES status(id);


-- Event log
ALTER TABLE event_log
    ADD CONSTRAINT fk_event_log_event_definition
        FOREIGN KEY (event_definition_id) REFERENCES event_definition(id);

ALTER TABLE event_log
    ADD CONSTRAINT fk_event_log_employee
        FOREIGN KEY (employee_id) REFERENCES employee(id);

ALTER TABLE event_log_entity
    ADD CONSTRAINT fk_event_log_entity_event_log
        FOREIGN KEY (event_log_id) REFERENCES event_log(id);