CREATE TABLE customer_contact (
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  customer_id INTEGER NOT NULL,
                                  name VARCHAR,
                                  phone_number VARCHAR NOT NULL,
                                  email VARCHAR NOT NULL,

                                  CONSTRAINT fk_customer_contact_customer
                                      FOREIGN KEY (customer_id)
                                          REFERENCES customer(id)
);